### ISSUE TITLE
Zelda 1 help

### ISSUE THREAD

**Issue by suncrisp** [mcclure/emu-coop#11]
Having beaten ALTTP and SM randomizer together, my friend and I wanted to try out Zelda 1. We both downloaded fceux and the emu-coop files, and ran the randomized ROM. when trying to connect to the IRC server his went fine; searching for partner. I, however, was prompted with a long "logging into server" message followed by a disconnect. We both followed the same steps.

**Comment by mcclure** [comment]
Can you run with "debug.lua" instead of "coop.lua"? Does anything interesting, like an error message, print in the lua console window if you do? (It's the same but it prints out more information about IRC connection etc.)

**Comment by suncrisp** [comment]
apparently by using sun or suncrisp as my nickname contains 'illegal characters'

**Comment by mcclure** [comment]
Baffling

Anyway this is probably a sign that it should be better about spotting and displaying error messages

**Comment by mcclure** [comment]
Ohh, wait, no, I'm really sorry, I know what's happening
You used "tab" to switch between boxes
On FCEUX only, "tab" gets actually entered into your name as a character, because the version of IUP is different
I need to do an update that strips the tabs out manually

Try entering "sun" as your name and then clicking to go to the next box instead of tabbing
