### ISSUE TITLE
Error using this with snes9x-rr. Missing files?

### ISSUE THREAD

**Issue by ANGELIX-sys** [mcclure/emu-coop#24]
This is my first time making an error/bug report, so if there's anything wrong with it or you need more information, please say so!

I am using the latest version of Snes9X-rr. I have downloaded the zip file that comes with the coop script bundled in, just in case. (I have tried it with the other one too, but it didn't work either.)
When I try to load the lua file coop.lua in Snex9X-rr, it gives me this error and no popups related to emu-coop happen.

---------------------------
Lua run error
---------------------------
.\modes\tloz_all.lua:12: module 'bit' not found:
	no field package.preload['bit']
	no file '.\bit.lua'
	no file 'C:\Users\jnrym\Downloads\snes9x-1.51-rerecording-svn-r51\lua\bit.lua'
	no file 'C:\Users\jnrym\Downloads\snes9x-1.51-rerecording-svn-r51\lua\bit\init.lua'
	no file 'C:\Users\jnrym\Downloads\snes9x-1.51-rerecording-svn-r51\bit.lua'
	no file 'C:\Users\jnrym\Downloads\snes9x-1.51-rerecording-svn-r51\bit\init.lua'
	no file '.\bit.dll'
	no file 'C:\Users\jnrym\Downloads\snes9x-1.51-rerecording-svn-r51\bit.dll'
	no file 'C:\Users\jnrym\Downloads\snes9x-1.51-rerecording-svn-r51\loadall.dll'
---------------------------
OK   
---------------------------

I know this isn't really a bug and I'm probably doing something wrong, but could someone please help? I really would love to play this with someone! (Also, I saw the related issues, and apparently someone tried uninstalling VS2017 and installing VS2015. But that didn't work either.)

**Comment by mcclure** [comment]
hmmmmmmmmm

can you clarify— you're using "the latest" snes9x-rr— you mean one you built yourself, not the one i built?

"bit" is a library provided by luajit

so that's a really confusing error but it SOUNDS to me like snes9x-rr is building with "vanilla lua" instead of luajit?

it might be possible to fix this by dropping in http://bitop.luajit.org/

**Comment by ANGELIX-sys** [comment]
I am using v1.5.1 r51, also I will try that.
Edit: I just realized I have no idea what "drop in" means. Could you please explain?

**Comment by mcclure** [comment]
I'm sorry. Just to be clear. You say "you are using v1.5.1". Where did you get "v1.5.1" from?

When I made this I was not sure where to get an official snes9x-rr so i built my own. My distribution is slightly modded so it might have, for example, a different Lua engine. So this would be the same "version number" of snes9x-rr but there might be small differences because of how it was built.

By "drop in" I mean you would have to build the "bitop" linked at that URL into a .dll and place it inside the same folder as main.lua. This might be difficult. I have never done this before.

**Comment by ANGELIX-sys** [comment]
I got it from https://www.zophar.net/snes/snes9x-rr.html so that might be a problem.
(I'm sorry too) I have no idea how programming works at all, so I will try installing your version of snes9x-rr and see if that helps.
Edit: I have no idea which file is the actual file in your version of snes9x-rr. None of them are executables that I can use so I don't know.

**Comment by mcclure** [comment]
I am sorry about the confusion.

Here https://github.com/mcclure/emu-coop/releases/download/1.2/snes9x-coop-1.2.zip is the copy of SNES9x-rr I built. It comes with a copy of the emu-coop script.

The program to run is snes9x.exe.

This requires Microsoft Windows. Are you on Windows?

EDIT: Also, there are additional instructions at https://mcclure.github.io/emu-coop/ — have you seen these?

**Comment by ANGELIX-sys** [comment]
OH, I had the wrong emulator zip installed apparently...
Yes, I am on windows.
Also, yay! After finally knowing which combination of things I have to use, I finally got the program working. Thanks so much! (I had to use the link you provided with coop.lua, like the directions said, I just didn't know where to get the right version of snes9x-rr.)
